import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  createGridfinityFootGeometry,
  DEFAULT_GRIDFINITY_FOOT_PLATE_THICKNESS,
  GRIDFINITY_FOOT_CORNER_SEGMENTS,
  GRIDFINITY_FOOT_GAP,
  GRIDFINITY_FOOT_HEIGHT,
  GRIDFINITY_FOOT_PROFILE,
  GRIDFINITY_FOOT_TOP_RADIUS,
  GRIDFINITY_FOOT_TOP_SIZE,
  GRIDFINITY_PITCH,
  gridfinityFootDimensions,
  gridfinityFootPositions,
  gridfinityFootTestPieceOptions,
} from "@/lib/gridfinityFootGeometry";
import { analyzeTriangleSoup } from "@/lib/svgImport";

// The foot test piece generated by
// scripts/generate-gridfinity-foot-test-piece.mjs. Both that script and
// these tests read gridfinityFootTestPieceOptions(), so there is one copy of
// the numbers, not two to keep in sync.
const TEST_PIECE_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../test-prints/gridfinity-foot-test-piece.stl");
const TEST_PIECE_OPTIONS = gridfinityFootTestPieceOptions();

// The foot as measured from the owner's reference Gridfinity STL
// (socket_tray_3-8dr_metric_6-14.stl), typed out by hand here rather than
// read back from the module, so a change to the module's profile cannot
// pass unnoticed.
const MEASURED_PROFILE = [
  { height: 0, size: 35.6, radius: 0.8 },
  { height: 0.8, size: 37.2, radius: 1.6 },
  { height: 2.6, size: 37.2, radius: 1.6 },
  { height: 4.75, size: 41.5, radius: 3.75 },
];

const GRIDS: Array<[number, number]> = [
  [1, 1],
  [2, 1],
  [1, 2],
  [3, 2],
  [3, 3],
  [4, 2],
];

// Same text the generator writes, byte for byte: ASCII STL, scene
// [x, y, z] -> file [x, -z, y], normals from the file-space vertices.
function toStlText(positions: readonly number[]): string {
  const lines = ["solid gridfinity_foot_test_piece"];
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const toZUp = (x: number, y: number, z: number) => [x, -z, y] as const;
    const a = toZUp(positions[i], positions[i + 1], positions[i + 2]);
    const b = toZUp(positions[i + 3], positions[i + 4], positions[i + 5]);
    const c = toZUp(positions[i + 6], positions[i + 7], positions[i + 8]);
    const ux = b[0] - a[0];
    const uy = b[1] - a[1];
    const uz = b[2] - a[2];
    const vx = c[0] - a[0];
    const vy = c[1] - a[1];
    const vz = c[2] - a[2];
    const nx = uy * vz - uz * vy;
    const ny = uz * vx - ux * vz;
    const nz = ux * vy - uy * vx;
    const length = Math.hypot(nx, ny, nz) || 1;
    lines.push(
      `  facet normal ${nx / length} ${ny / length} ${nz / length}`,
      "    outer loop",
      `      vertex ${a[0]} ${a[1]} ${a[2]}`,
      `      vertex ${b[0]} ${b[1]} ${b[2]}`,
      `      vertex ${c[0]} ${c[1]} ${c[2]}`,
      "    endloop",
      "  endfacet",
    );
  }
  lines.push("endsolid gridfinity_foot_test_piece");
  return lines.join("\n") + "\n";
}

function parseStlToScenePositions(stl: string): number[] {
  const positions: number[] = [];
  const vertexPattern = /vertex\s+(-?[\d.eE+-]+)\s+(-?[\d.eE+-]+)\s+(-?[\d.eE+-]+)/g;
  let match: RegExpExecArray | null;
  while ((match = vertexPattern.exec(stl))) {
    const fx = Number(match[1]);
    const fy = Number(match[2]);
    const fz = Number(match[3]);
    // Inverse of [x, y, z] -> [x, -z, y]: scene x = file x, scene y = file z, scene z = -file y.
    // "0 - fy" rather than "-fy" so a file 0 comes back as 0, not -0.
    positions.push(fx, fz, 0 - fy);
  }
  return positions;
}

// Every directed edge must appear exactly once, with its reverse exactly
// once, keyed on the raw doubles -- the exact-stitch contract from
// CLAUDE-LESSONS.md. Returns the offending edges rather than asserting per
// edge, so a failure prints a short list instead of thousands of lines.
function directedEdgeDefects(positions: readonly number[]): string[] {
  const directed = new Map<string, number>();
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const keys = [0, 3, 6].map((offset) => `${positions[i + offset]},${positions[i + offset + 1]},${positions[i + offset + 2]}`);
    for (let edge = 0; edge < 3; edge += 1) {
      const key = `${keys[edge]}|${keys[(edge + 1) % 3]}`;
      directed.set(key, (directed.get(key) ?? 0) + 1);
    }
  }
  const defects: string[] = [];
  for (const [key, count] of directed) {
    const [a, b] = key.split("|");
    if (count !== 1 || directed.get(`${b}|${a}`) !== 1) defects.push(key);
  }
  return defects;
}

// Heights at which a vertical ray through (x, z) crosses the mesh, lowest
// first, coincident crossings merged.
function verticalCrossings(positions: readonly number[], x: number, z: number): number[] {
  const crossings: number[] = [];
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const p = positions;
    const denom = (p[i + 5] - p[i + 8]) * (p[i] - p[i + 6]) + (p[i + 6] - p[i + 3]) * (p[i + 2] - p[i + 8]);
    if (Math.abs(denom) < 1e-12) continue;
    const a = ((p[i + 5] - p[i + 8]) * (x - p[i + 6]) + (p[i + 6] - p[i + 3]) * (z - p[i + 8])) / denom;
    const b = ((p[i + 8] - p[i + 2]) * (x - p[i + 6]) + (p[i] - p[i + 6]) * (z - p[i + 8])) / denom;
    const c = 1 - a - b;
    if (a < 0 || b < 0 || c < 0) continue;
    crossings.push(a * p[i + 1] + b * p[i + 4] + c * p[i + 7]);
  }
  crossings.sort((m, n) => m - n);
  return crossings.filter((y, index) => index === 0 || y - crossings[index - 1] > 1e-9);
}

// X positions at which a ray along +X at height y and depth z crosses the
// mesh, lowest first, coincident crossings merged.
function crossingsAlongX(positions: readonly number[], y: number, z: number): number[] {
  const crossings: number[] = [];
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const p = positions;
    // Barycentric coordinates of (y, z) in the triangle's (y, z) projection.
    const denom = (p[i + 5] - p[i + 8]) * (p[i + 1] - p[i + 7]) + (p[i + 7] - p[i + 4]) * (p[i + 2] - p[i + 8]);
    if (Math.abs(denom) < 1e-12) continue;
    const a = ((p[i + 5] - p[i + 8]) * (y - p[i + 7]) + (p[i + 7] - p[i + 4]) * (z - p[i + 8])) / denom;
    const b = ((p[i + 8] - p[i + 2]) * (y - p[i + 7]) + (p[i + 1] - p[i + 7]) * (z - p[i + 8])) / denom;
    const c = 1 - a - b;
    if (a < 0 || b < 0 || c < 0) continue;
    crossings.push(a * p[i] + b * p[i + 3] + c * p[i + 6]);
  }
  crossings.sort((m, n) => m - n);
  return crossings.filter((x, index) => index === 0 || x - crossings[index - 1] > 1e-9);
}

// Measures one foot of a mesh the way the reference STL was measured: from
// the vertices of the foot's own walls standing at `height` inside that
// foot's 42mm square. Only wall triangles are read (those that also reach
// the neighbouring profile level), so the plate's underside, which shares
// the foot top's height, is left out. Plan size is the vertices' extent; the
// corner radius is read from where the straight edge on the high-X side
// stops, and checked against the distance of every corner point from the
// arc's centre.
function measureFoot(positions: readonly number[], column: number, row: number, height: number) {
  const points = new Map<string, [number, number]>();
  const lowX = GRIDFINITY_PITCH * column - GRIDFINITY_FOOT_GAP / 2;
  const lowZ = GRIDFINITY_PITCH * row - GRIDFINITY_FOOT_GAP / 2;
  const index = MEASURED_PROFILE.findIndex((level) => level.height === height);
  const neighbour = MEASURED_PROFILE[index === 0 ? 1 : index - 1].height;
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const heights = [positions[i + 1], positions[i + 4], positions[i + 7]];
    if (!heights.some((y) => Math.abs(y - neighbour) < 1e-9)) continue;
    for (let vertex = 0; vertex < 3; vertex += 1) {
      if (Math.abs(heights[vertex] - height) > 1e-9) continue;
      const x = positions[i + vertex * 3];
      const z = positions[i + vertex * 3 + 2];
      if (x < lowX || x > lowX + GRIDFINITY_PITCH || z < lowZ || z > lowZ + GRIDFINITY_PITCH) continue;
      points.set(`${x},${z}`, [x, z]);
    }
  }
  const all = [...points.values()];
  const minX = Math.min(...all.map((point) => point[0]));
  const maxX = Math.max(...all.map((point) => point[0]));
  const minZ = Math.min(...all.map((point) => point[1]));
  const maxZ = Math.max(...all.map((point) => point[1]));
  const onHighX = all.filter((point) => Math.abs(point[0] - maxX) < 1e-9).map((point) => point[1]);
  const radius = maxZ - Math.max(...onHighX);
  const arcCentre = [maxX - radius, maxZ - radius];
  const arc = all.filter((point) => point[0] >= arcCentre[0] - 1e-9 && point[1] >= arcCentre[1] - 1e-9);
  const distances = arc.map((point) => Math.hypot(point[0] - arcCentre[0], point[1] - arcCentre[1]));
  return {
    sizeX: maxX - minX,
    sizeZ: maxZ - minZ,
    centreX: (minX + maxX) / 2,
    centreZ: (minZ + maxZ) / 2,
    radius,
    arcPoints: arc.length,
    arcRadiusMin: Math.min(...distances),
    arcRadiusMax: Math.max(...distances),
  };
}

// Asserts a list of crossings against the expected one. Crossings are
// interpolated across a triangle, so they are compared to 1e-9, not exactly.
function expectCrossings(actual: number[], expected: number[]) {
  expect(actual.length, `crossings [${actual.join(", ")}]`).toBe(expected.length);
  expected.forEach((value, index) => expect(actual[index]).toBeCloseTo(value, 9));
}

// Area of a rounded square whose corner arcs are polygons of
// GRIDFINITY_FOOT_CORNER_SEGMENTS segments, as the mesh builds them.
function outlineArea(sizeX: number, sizeZ: number, radius: number): number {
  const segments = 4 * GRIDFINITY_FOOT_CORNER_SEGMENTS;
  const cornerPolygons = (segments / 2) * radius * radius * Math.sin((2 * Math.PI) / segments);
  return sizeX * sizeZ - 4 * radius * radius + cornerPolygons;
}

// Volume of one foot: between two levels the outline's size and radius run
// linearly, so its area is a quadratic in height and Simpson's rule is
// exact.
function footVolume(): number {
  let volume = 0;
  for (let level = 0; level + 1 < MEASURED_PROFILE.length; level += 1) {
    const low = MEASURED_PROFILE[level];
    const high = MEASURED_PROFILE[level + 1];
    const middleSize = (low.size + high.size) / 2;
    const middleRadius = (low.radius + high.radius) / 2;
    volume +=
      ((high.height - low.height) / 6) *
      (outlineArea(low.size, low.size, low.radius) + 4 * outlineArea(middleSize, middleSize, middleRadius) + outlineArea(high.size, high.size, high.radius));
  }
  return volume;
}

describe("gridfinity foot: the measured profile", () => {
  it("is the profile measured from the owner's reference STL", () => {
    expect(GRIDFINITY_FOOT_PROFILE.map((level) => ({ ...level }))).toEqual(MEASURED_PROFILE);
    expect(GRIDFINITY_FOOT_HEIGHT).toBe(4.75);
    expect(GRIDFINITY_FOOT_TOP_SIZE).toBe(41.5);
    expect(GRIDFINITY_FOOT_TOP_RADIUS).toBe(3.75);
    expect(GRIDFINITY_PITCH).toBe(42);
    expect(GRIDFINITY_FOOT_GAP).toBe(0.5);
    expect(GRIDFINITY_PITCH - GRIDFINITY_FOOT_TOP_SIZE).toBe(GRIDFINITY_FOOT_GAP);
    expect(GRIDFINITY_FOOT_CORNER_SEGMENTS).toBe(16);
  });

  it("is a 0.8mm chamfer, a 1.8mm straight band and a 2.15mm chamfer, both chamfers at 45 degrees", () => {
    const [bed, lowerTop, straightTop, top] = GRIDFINITY_FOOT_PROFILE;
    expect(lowerTop.height - bed.height).toBeCloseTo(0.8, 12);
    expect(straightTop.height - lowerTop.height).toBeCloseTo(1.8, 12);
    expect(top.height - straightTop.height).toBeCloseTo(2.15, 12);
    // 45 degrees: the outline grows by the chamfer's height on every side.
    expect((lowerTop.size - bed.size) / 2).toBeCloseTo(0.8, 12);
    expect(straightTop.size).toBe(lowerTop.size);
    expect((top.size - straightTop.size) / 2).toBeCloseTo(2.15, 12);
  });

  it("keeps the corner arcs concentric at every height", () => {
    for (const level of GRIDFINITY_FOOT_PROFILE) expect(level.size / 2 - level.radius).toBeCloseTo(17, 12);
  });
});

describe("gridfinityFootDimensions", () => {
  it("sizes the piece from its squares: 42 per square less the 0.5mm gap", () => {
    expect(gridfinityFootDimensions({ squaresX: 1, squaresZ: 1 })).toMatchObject({ width: 41.5, depth: 41.5, height: 7.75 });
    expect(gridfinityFootDimensions({ squaresX: 2, squaresZ: 1 })).toMatchObject({ width: 83.5, depth: 41.5 });
    // The owner's two reference exports: 3 x 2 and 4 x 2.
    expect(gridfinityFootDimensions({ squaresX: 3, squaresZ: 2 })).toMatchObject({ width: 125.5, depth: 83.5 });
    expect(gridfinityFootDimensions({ squaresX: 4, squaresZ: 2 })).toMatchObject({ width: 167.5, depth: 83.5 });
  });

  it("adds the plate thickness to the 4.75mm foot", () => {
    expect(DEFAULT_GRIDFINITY_FOOT_PLATE_THICKNESS).toBe(3);
    expect(gridfinityFootDimensions({ squaresX: 1, squaresZ: 1 }).plateThickness).toBe(3);
    expect(gridfinityFootDimensions({ squaresX: 1, squaresZ: 1, plateThickness: 5 }).height).toBe(9.75);
  });

  it("throws on anything but a whole number of squares, 1 or more", () => {
    expect(() => gridfinityFootDimensions({ squaresX: 0, squaresZ: 1 })).toThrow(/squaresX must be a whole number of squares, 1 or more \(got 0\)/);
    expect(() => gridfinityFootDimensions({ squaresX: 2, squaresZ: 1.5 })).toThrow(/squaresZ must be a whole number of squares/);
    expect(() => gridfinityFootDimensions({ squaresX: -1, squaresZ: 1 })).toThrow(/squaresX must be a whole number/);
    expect(() => gridfinityFootDimensions({ squaresX: Number.NaN, squaresZ: 1 })).toThrow(/squaresX must be a whole number/);
  });

  it("throws on a non-positive plate thickness", () => {
    expect(() => gridfinityFootDimensions({ squaresX: 1, squaresZ: 1, plateThickness: 0 })).toThrow(/plate thickness must be positive/);
    expect(() => gridfinityFootDimensions({ squaresX: 1, squaresZ: 1, plateThickness: -2 })).toThrow(/plate thickness must be positive/);
  });
});

describe("gridfinityFootPositions: N x M grids", () => {
  for (const [squaresX, squaresZ] of GRIDS) {
    const name = `${squaresX} x ${squaresZ}`;
    const positions = gridfinityFootPositions({ squaresX, squaresZ });
    const dimensions = gridfinityFootDimensions({ squaresX, squaresZ });

    it(`${name}: watertight, manifold, exact directed-edge manifold`, () => {
      expect(positions.every(Number.isFinite)).toBe(true);
      const analysis = analyzeTriangleSoup(positions);
      expect(analysis.boundaryEdges).toBe(0);
      expect(analysis.nonManifoldEdges).toBe(0);
      expect(analysis.degenerateTriangles).toBe(0);
      expect(directedEdgeDefects(positions)).toEqual([]);
    });

    it(`${name}: volume is the plate plus ${squaresX * squaresZ} feet`, () => {
      const plate = outlineArea(dimensions.width, dimensions.depth, GRIDFINITY_FOOT_TOP_RADIUS) * dimensions.plateThickness;
      const analysis = analyzeTriangleSoup(positions);
      expect(Math.abs(analysis.volume)).toBeCloseTo(plate + squaresX * squaresZ * footVolume(), 6);
      // Signed, from the raw triangles: positive means every face is wound
      // outward, which the directed-edge test alone cannot tell from every
      // face wound inward.
      let signed = 0;
      for (let i = 0; i + 8 < positions.length; i += 9) {
        const [ax, ay, az, bx, by, bz, cx, cy, cz] = positions.slice(i, i + 9);
        signed += (ax * (by * cz - bz * cy) - ay * (bx * cz - bz * cx) + az * (bx * cy - by * cx)) / 6;
      }
      expect(signed).toBeGreaterThan(0);
    });

    it(`${name}: every foot measures the reference profile and sits on the 42mm pitch`, () => {
      for (let column = 0; column < squaresX; column += 1) {
        for (let row = 0; row < squaresZ; row += 1) {
          for (const level of MEASURED_PROFILE) {
            const measured = measureFoot(positions, column, row, level.height);
            expect(measured.sizeX).toBeCloseTo(level.size, 9);
            expect(measured.sizeZ).toBeCloseTo(level.size, 9);
            expect(measured.radius).toBeCloseTo(level.radius, 9);
            expect(measured.arcPoints).toBe(GRIDFINITY_FOOT_CORNER_SEGMENTS + 1);
            expect(measured.arcRadiusMin).toBeCloseTo(level.radius, 9);
            expect(measured.arcRadiusMax).toBeCloseTo(level.radius, 9);
            expect(measured.centreX).toBeCloseTo(20.75 + 42 * column, 9);
            expect(measured.centreZ).toBeCloseTo(20.75 + 42 * row, 9);
          }
        }
      }
    });
  }

  // 3 x 3 is the smallest grid with a foot that touches no edge of the
  // plate: all four of its corners carry a fan and all four of its sides a
  // strip.
  it("3 x 3: the plate's underside is open to the bed between every pair of feet, and closed by a foot under every square", () => {
    const positions = gridfinityFootPositions({ squaresX: 3, squaresZ: 3 });
    for (let column = 0; column < 3; column += 1) {
      for (let row = 0; row < 3; row += 1) {
        const x = 20.75 + 42 * column;
        const z = 20.75 + 42 * row;
        expectCrossings(verticalCrossings(positions, x + 0.013, z + 0.007), [0, 7.75]);
        // In the 0.5mm gap beside this foot, and where four gaps cross.
        if (column < 2) expectCrossings(verticalCrossings(positions, x + 21, z + 0.007), [4.75, 7.75]);
        if (row < 2) expectCrossings(verticalCrossings(positions, x + 0.013, z + 21), [4.75, 7.75]);
        if (column < 2 && row < 2) expectCrossings(verticalCrossings(positions, x + 21.013, z + 21.007), [4.75, 7.75]);
      }
    }
  });
});

describe("gridfinityFootPositions: foot test piece", () => {
  const positions = gridfinityFootPositions(TEST_PIECE_OPTIONS);
  const dimensions = gridfinityFootDimensions(TEST_PIECE_OPTIONS);

  it("is 2 x 1 Gridfinity squares under a 3mm plate", () => {
    expect(TEST_PIECE_OPTIONS).toEqual({ squaresX: 2, squaresZ: 1, plateThickness: 3 });
    expect(dimensions).toMatchObject({ width: 83.5, depth: 41.5, height: 7.75, plateThickness: 3 });
  });

  it("bounding box is 83.5 x 7.75 x 41.5mm from the origin", () => {
    const box = createGridfinityFootGeometry(TEST_PIECE_OPTIONS).boundingBox!;
    expect(box.min.x).toBeCloseTo(0, 6);
    expect(box.max.x).toBeCloseTo(83.5, 5);
    expect(box.min.y).toBeCloseTo(0, 6);
    expect(box.max.y).toBeCloseTo(7.75, 6);
    expect(box.min.z).toBeCloseTo(0, 6);
    expect(box.max.z).toBeCloseTo(41.5, 5);
  });

  it("fits the Bambu X1C bed (256 x 256mm)", () => {
    expect(dimensions.width).toBeLessThan(256);
    expect(dimensions.depth).toBeLessThan(256);
  });

  it("the mesh has exactly five levels: bed, two chamfer edges, foot top, plate top", () => {
    const levels = new Set<number>();
    for (let i = 1; i < positions.length; i += 3) levels.add(positions[i]);
    expect([...levels].sort((a, b) => a - b)).toEqual([0, 0.8, 2.6, 4.75, 7.75]);
  });

  it("the two feet stand 42mm apart, centre to centre, 0.5mm apart at their tops", () => {
    const left = measureFoot(positions, 0, 0, 4.75);
    const right = measureFoot(positions, 1, 0, 4.75);
    expect(right.centreX - left.centreX).toBeCloseTo(42, 9);
    expect(right.centreX - right.sizeX / 2 - (left.centreX + left.sizeX / 2)).toBeCloseTo(0.5, 9);
  });

  it("the plate's plan corner radius is the foot top's 3.75mm", () => {
    const onHighX: number[] = [];
    for (let i = 0; i + 2 < positions.length; i += 3) {
      if (positions[i + 1] === 7.75 && positions[i] === 83.5) onHighX.push(positions[i + 2]);
    }
    expect(Math.min(...onHighX)).toBe(3.75);
    expect(Math.max(...onHighX)).toBe(37.75);
  });
});

// A mesh can be closed and still be the wrong shape (CLAUDE-LESSONS.md), so
// raycast the EXPORTED FILE: open where it must be open -- under the plate
// between the feet, and beside each chamfer -- and solid where it must be
// solid.
describe("test-prints/gridfinity-foot-test-piece.stl", () => {
  const file = readFileSync(TEST_PIECE_PATH, "utf8");
  const filePositions = parseStlToScenePositions(file);

  it("is exactly what the module produces, byte for byte", () => {
    const expected = toStlText(gridfinityFootPositions(TEST_PIECE_OPTIONS));
    expect(file.length).toBe(expected.length);
    expect(file === expected).toBe(true);
    expect(file.split("\n").filter((line) => line.startsWith("  facet normal")).length).toBe(1250);
  });

  it("the file itself is watertight, manifold and exact directed-edge manifold", () => {
    const analysis = analyzeTriangleSoup(filePositions);
    expect(analysis.triangleCount).toBe(1250);
    expect(analysis.boundaryEdges).toBe(0);
    expect(analysis.nonManifoldEdges).toBe(0);
    expect(analysis.degenerateTriangles).toBe(0);
    expect(directedEdgeDefects(filePositions)).toEqual([]);
  });

  it("the file's bounding box is 83.5 x 41.5 x 7.75mm", () => {
    const analysis = analyzeTriangleSoup(filePositions);
    // Scene axes: width along X, height along Y (up), depth along Z.
    expect(analysis.width).toBeCloseTo(83.5, 9);
    expect(analysis.depth).toBeCloseTo(41.5, 9);
    expect(analysis.height).toBeCloseTo(7.75, 9);
  });

  it("every foot in the file measures the reference profile", () => {
    for (const column of [0, 1]) {
      for (const level of MEASURED_PROFILE) {
        const measured = measureFoot(filePositions, column, 0, level.height);
        expect(measured.sizeX).toBeCloseTo(level.size, 9);
        expect(measured.sizeZ).toBeCloseTo(level.size, 9);
        expect(measured.radius).toBeCloseTo(level.radius, 9);
        expect(measured.arcRadiusMin).toBeCloseTo(level.radius, 9);
        expect(measured.arcRadiusMax).toBeCloseTo(level.radius, 9);
      }
    }
  });

  it("solid from bed to plate top under each foot, open under the plate between the feet", () => {
    for (const column of [0, 1]) {
      const centreX = 20.75 + 42 * column;
      // Inside the 35.6mm bed face, off its centre and off every edge.
      for (const [dx, dz] of [
        [0.013, 0.007],
        [17.013, 0.007],
        [-17.013, 0.007],
        [0.013, 17.007],
        [0.013, -17.007],
        [17.513, 17.507],
      ]) {
        expectCrossings(verticalCrossings(filePositions, centreX + dx, 20.75 + dz), [0, 7.75]);
      }
    }
    // The 0.5mm gap between the feet, along its whole length.
    for (const z of [0.107, 3.757, 10.007, 20.757, 31.007, 37.743, 41.393]) {
      expectCrossings(verticalCrossings(filePositions, 41.763, z), [4.75, 7.75]);
    }
    // In the corners beside the gap, outside both feet's corner arcs.
    for (const [x, z] of [
      [41.013, 0.507],
      [42.487, 0.507],
      [41.013, 40.993],
      [42.487, 40.993],
    ]) {
      expectCrossings(verticalCrossings(filePositions, x, z), [4.75, 7.75]);
    }
  });

  it("the chamfers are where the profile puts them", () => {
    // Over the upper chamfer, 1mm in from the foot top's edge: the underside
    // stands 1mm below the foot top. Over the lower chamfer, 0.4mm in from
    // the straight band: 0.4mm below the chamfer's top.
    for (const column of [0, 1]) {
      const lowX = 42 * column;
      const upper = verticalCrossings(filePositions, lowX + 1, 20.757);
      expectCrossings(upper, [3.75, 7.75]);
      const lower = verticalCrossings(filePositions, lowX + 2.15 + 0.4, 20.757);
      expectCrossings(lower, [0.4, 7.75]);
    }
  });

  it("a ray along the piece meets two separate feet below the plate and one plate above them", () => {
    // Through the straight band (37.2mm wide, 2.15mm in from each foot top
    // edge): foot, 4.8mm of open air, foot.
    const band = crossingsAlongX(filePositions, 1.7, 20.757);
    expectCrossings(band, [2.15, 39.35, 44.15, 81.35]);
    // On the bed face's level, just above it (35.6mm wide at the bed).
    const bed = crossingsAlongX(filePositions, 0.001, 20.757);
    expectCrossings(bed, [2.949, 38.551, 44.949, 80.551]);
    // Through the plate: one piece, edge to edge.
    expectCrossings(crossingsAlongX(filePositions, 6.2, 20.757), [0, 83.5]);
  });
});
