import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  createLabelSlabGeometry,
  DEFAULT_LABEL_SLAB_GAP,
  DEFAULT_LABEL_SLAB_MARGIN,
  LABEL_BAND_BOTTOM,
  LABEL_BAND_TOP,
  LABEL_CHARACTERS,
  LABEL_DEPTH,
  LABEL_DIGIT_HEIGHT,
  LABEL_TEST_PIECE_SOCKET_SIZES,
  labelOutline,
  labelSlabLayout,
  labelSlabPositions,
  labelTestPieceOptions,
  socketSizeLabel,
  type LabelGlyphOutline,
  type LabelSlabOptions,
  type LabelStyle,
} from "@/lib/labelSlabGeometry";
import { analyzeTriangleSoup } from "@/lib/svgImport";

// The label test piece generated by scripts/generate-label-test-piece.mjs.
// Both that script and these tests read labelTestPieceOptions(), so there is
// one copy of the layout, not two to keep in sync.
const TEST_PIECE_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../test-prints/label-test-piece.stl");
const TEST_PIECE_OPTIONS = labelTestPieceOptions();

// The owner's socket set, typed out by hand here rather than read back from
// the module, so a change to the module's list cannot pass unnoticed.
const SOCKET_LABELS = ["5mm", "6mm", "7mm", "8mm", "9mm", "10mm", "11mm", "12mm", "13mm", "14mm", "15mm", "16mm"];
const STYLES: LabelStyle[] = ["raised", "recessed"];

type Point2 = readonly [number, number];

// Same text the generator writes, byte for byte: ASCII STL, scene
// [x, y, z] -> file [x, -z, y], normals from the file-space vertices.
function toStlText(positions: readonly number[]): string {
  const lines = ["solid label_test_piece"];
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const toZUp = (x: number, y: number, z: number) => [x, -z, y] as const;
    const a = toZUp(positions[i], positions[i + 1], positions[i + 2]);
    const b = toZUp(positions[i + 3], positions[i + 4], positions[i + 5]);
    const c = toZUp(positions[i + 6], positions[i + 7], positions[i + 8]);
    const ux = b[0] - a[0];
    const uy = b[1] - a[1];
    const uz = b[2] - a[2];
    const vx = c[0] - a[0];
    const vy = c[1] - a[1];
    const vz = c[2] - a[2];
    const nx = uy * vz - uz * vy;
    const ny = uz * vx - ux * vz;
    const nz = ux * vy - uy * vx;
    const length = Math.hypot(nx, ny, nz) || 1;
    lines.push(
      `  facet normal ${nx / length} ${ny / length} ${nz / length}`,
      "    outer loop",
      `      vertex ${a[0]} ${a[1]} ${a[2]}`,
      `      vertex ${b[0]} ${b[1]} ${b[2]}`,
      `      vertex ${c[0]} ${c[1]} ${c[2]}`,
      "    endloop",
      "  endfacet",
    );
  }
  lines.push("endsolid label_test_piece");
  return lines.join("\n") + "\n";
}

function parseStlToScenePositions(stl: string): number[] {
  const positions: number[] = [];
  const vertexPattern = /vertex\s+(-?[\d.eE+-]+)\s+(-?[\d.eE+-]+)\s+(-?[\d.eE+-]+)/g;
  let match: RegExpExecArray | null;
  while ((match = vertexPattern.exec(stl))) {
    const fx = Number(match[1]);
    const fy = Number(match[2]);
    const fz = Number(match[3]);
    // Inverse of [x, y, z] -> [x, -z, y]: scene x = file x, scene y = file z, scene z = -file y.
    // "0 - fy" rather than "-fy" so a file 0 comes back as 0, not -0.
    positions.push(fx, fz, 0 - fy);
  }
  return positions;
}

// Every directed edge must appear exactly once, with its reverse exactly
// once, keyed on the raw doubles -- the exact-stitch contract from
// CLAUDE-LESSONS.md. Returns the offending edges rather than asserting per
// edge, so a failure prints a short list instead of thousands of lines.
function directedEdgeDefects(positions: readonly number[]): string[] {
  const directed = new Map<string, number>();
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const keys = [0, 3, 6].map((offset) => `${positions[i + offset]},${positions[i + offset + 1]},${positions[i + offset + 2]}`);
    for (let edge = 0; edge < 3; edge += 1) {
      const key = `${keys[edge]}|${keys[(edge + 1) % 3]}`;
      directed.set(key, (directed.get(key) ?? 0) + 1);
    }
  }
  const defects: string[] = [];
  for (const [key, count] of directed) {
    const [a, b] = key.split("|");
    if (count !== 1 || directed.get(`${b}|${a}`) !== 1) defects.push(key);
  }
  return defects;
}

function pointInLoop(loop: readonly Point2[], x: number, y: number): boolean {
  let inside = false;
  for (let i = 0, j = loop.length - 1; i < loop.length; j = i, i += 1) {
    const [xi, yi] = loop[i];
    const [xj, yj] = loop[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

function distanceToLoop(loop: readonly Point2[], x: number, y: number): number {
  let best = Number.POSITIVE_INFINITY;
  for (let i = 0; i < loop.length; i += 1) {
    const [ax, ay] = loop[i];
    const [bx, by] = loop[(i + 1) % loop.length];
    const dx = bx - ax;
    const dy = by - ay;
    const t = Math.max(0, Math.min(1, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy)));
    best = Math.min(best, Math.hypot(x - (ax + t * dx), y - (ay + t * dy)));
  }
  return best;
}

function segmentsCross(a: Point2, b: Point2, c: Point2, d: Point2): boolean {
  const side = (p: Point2, q: Point2, r: Point2) => Math.sign((q[0] - p[0]) * (r[1] - p[1]) - (q[1] - p[1]) * (r[0] - p[0]));
  return side(a, b, c) !== side(a, b, d) && side(c, d, a) !== side(c, d, b);
}

function allLoops(glyph: LabelGlyphOutline): Point2[][] {
  return [glyph.outer, ...glyph.holes];
}

describe("label outlines", () => {
  it("the digit set 0-9 measures exactly 5.00mm tall on a shared baseline", () => {
    const digits = labelOutline("0123456789");
    expect(LABEL_DIGIT_HEIGHT).toBe(5);
    expect(Math.abs(digits.maxY - digits.minY - 5)).toBeLessThan(1e-12);
    expect(Math.abs(LABEL_BAND_TOP - LABEL_BAND_BOTTOM - 5)).toBeLessThan(1e-12);
    expect(digits.minY).toBe(LABEL_BAND_BOTTOM);
    expect(digits.maxY).toBe(LABEL_BAND_TOP);
    // NOT font size 5, which would make the same digits 5.105mm.
    expect(digits.maxY - digits.minY).not.toBeCloseTo(5.105, 2);
  });

  it("every digit fits the 5mm band; none is taller than 5mm or shorter than 4.69mm", () => {
    const heights: Record<string, number> = {};
    for (const digit of "0123456789") {
      const outline = labelOutline(digit);
      expect(outline.minY).toBeGreaterThanOrEqual(LABEL_BAND_BOTTOM);
      expect(outline.maxY).toBeLessThanOrEqual(LABEL_BAND_TOP);
      heights[digit] = outline.maxY - outline.minY;
    }
    // Helvetiker bold's digits are not all one height: 4 and 7 are the
    // shortest, 3 the tallest. Pinned so a font or scale change is loud.
    expect(heights["4"]).toBeCloseTo(4.6915, 3);
    expect(heights["7"]).toBeCloseTo(4.6915, 3);
    expect(heights["1"]).toBeCloseTo(4.8188, 3);
    expect(heights["3"]).toBeCloseTo(4.9853, 3);
    expect(Math.max(...Object.values(heights))).toBeLessThanOrEqual(5);
    expect(Math.min(...Object.values(heights))).toBeGreaterThan(4.69);
  });

  it("the letter m sits on the baseline, inside the digit band", () => {
    const m = labelOutline("m");
    expect(m.minY).toBe(0);
    expect(m.maxY).toBeLessThan(LABEL_BAND_TOP);
  });

  it("each accepted character is one outline with the expected counters", () => {
    const counters: Record<string, number> = { "0": 1, "4": 1, "6": 1, "8": 2, "9": 1 };
    for (const character of LABEL_CHARACTERS) {
      const outline = labelOutline(character);
      expect(outline.glyphs.length, `"${character}" outline count`).toBe(1);
      expect(outline.glyphs[0].holes.length, `"${character}" counter count`).toBe(counters[character] ?? 0);
    }
  });

  it("outlines carry no repeated points and no exactly collinear points", () => {
    for (const character of LABEL_CHARACTERS) {
      for (const loop of allLoops(labelOutline(character).glyphs[0])) {
        expect(loop.length).toBeGreaterThanOrEqual(3);
        for (let i = 0; i < loop.length; i += 1) {
          const previous = loop[(i - 1 + loop.length) % loop.length];
          const current = loop[i];
          const next = loop[(i + 1) % loop.length];
          expect(current[0] === next[0] && current[1] === next[1], `"${character}" repeated point at ${i}`).toBe(false);
          const cross = (current[1] - previous[1]) * (next[0] - current[0]) - (current[0] - previous[0]) * (next[1] - current[1]);
          expect(cross, `"${character}" collinear point at ${i}`).not.toBe(0);
        }
      }
    }
  });

  // Font glyphs are not CAD contours (recon risk 1): prove each accepted
  // character is a simple polygon with its counters strictly inside it.
  it("outlines do not self-intersect, and counters lie inside their glyph without touching it", () => {
    for (const character of LABEL_CHARACTERS) {
      const glyph = labelOutline(character).glyphs[0];
      const loops = allLoops(glyph);
      const segments: Array<{ loop: number; index: number; a: Point2; b: Point2; count: number }> = [];
      loops.forEach((loop, loopIndex) => {
        loop.forEach((point, index) => segments.push({ loop: loopIndex, index, a: point, b: loop[(index + 1) % loop.length], count: loop.length }));
      });
      for (let i = 0; i < segments.length; i += 1) {
        for (let j = i + 1; j < segments.length; j += 1) {
          const s = segments[i];
          const t = segments[j];
          if (s.loop === t.loop) {
            const apart = Math.abs(s.index - t.index);
            if (apart === 1 || apart === s.count - 1) continue;
          }
          expect(segmentsCross(s.a, s.b, t.a, t.b), `"${character}" loops ${s.loop}/${t.loop} segments ${s.index}/${t.index} cross`).toBe(false);
        }
      }
      for (const hole of glyph.holes) {
        for (const [x, y] of hole) expect(pointInLoop(glyph.outer, x, y), `"${character}" counter point outside its glyph`).toBe(true);
      }
    }
  });

  it("rejects characters outside the accepted set, and empty text", () => {
    expect(() => labelOutline("5 mm")).toThrow(/only the characters 0123456789m are supported/);
    expect(() => labelOutline("5MM")).toThrow(/contains "M"/);
    expect(() => labelOutline("")).toThrow(/must not be empty/);
  });
});

describe("labelSlabPositions: every socket label, one at a time", () => {
  for (const style of STYLES) {
    for (const text of SOCKET_LABELS) {
      it(`"${text}" ${style}: watertight, manifold, exact directed-edge manifold`, () => {
        const positions = labelSlabPositions({ rows: [[{ text, style }]] });
        expect(positions.every(Number.isFinite)).toBe(true);
        const analysis = analyzeTriangleSoup(positions);
        expect(analysis.boundaryEdges).toBe(0);
        expect(analysis.nonManifoldEdges).toBe(0);
        expect(analysis.degenerateTriangles).toBe(0);
        expect(directedEdgeDefects(positions)).toEqual([]);
      });
    }
  }

  // The glyphs of a label share one baseline, so earcut runs triangle edges
  // straight over the glyph corners lying on it. "12mm" is the label that
  // first showed it (4 open edges before the conforming pass); a second
  // label in the row moves it to different coordinates.
  it('"12mm" stays closed wherever it is placed', () => {
    for (const style of STYLES) {
      const positions = labelSlabPositions({
        rows: [
          [
            { text: "16mm", style },
            { text: "12mm", style },
          ],
          [
            { text: "12mm", style },
            { text: "5mm", style },
          ],
        ],
      });
      expect(directedEdgeDefects(positions)).toEqual([]);
    }
  });
});

describe("labelSlabPositions: label test piece", () => {
  const layout = labelSlabLayout(TEST_PIECE_OPTIONS);
  const positions = labelSlabPositions(TEST_PIECE_OPTIONS);

  it("carries every socket-size label twice: once raised, once recessed", () => {
    expect([...LABEL_TEST_PIECE_SOCKET_SIZES]).toEqual([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]);
    expect(LABEL_TEST_PIECE_SOCKET_SIZES.map(socketSizeLabel)).toEqual(SOCKET_LABELS);
    expect(layout.labels.length).toBe(24);
    for (const style of STYLES) {
      const texts = layout.labels.filter((label) => label.style === style).map((label) => label.text);
      expect([...texts].sort()).toEqual([...SOCKET_LABELS].sort());
    }
  });

  it("puts the two styles of one label side by side, 5mm top left to 16mm bottom right", () => {
    const at = (row: number, column: number) => layout.labels.find((label) => label.row === row && label.column === column)!;
    for (let row = 0; row < 6; row += 1) {
      expect(at(row, 0)).toMatchObject({ text: SOCKET_LABELS[row], style: "raised" });
      expect(at(row, 1)).toMatchObject({ text: SOCKET_LABELS[row], style: "recessed" });
      expect(at(row, 2)).toMatchObject({ text: SOCKET_LABELS[row + 6], style: "raised" });
      expect(at(row, 3)).toMatchObject({ text: SOCKET_LABELS[row + 6], style: "recessed" });
    }
    // Reading order: a lower row sits at larger Z, a later column at larger X.
    expect(at(1, 0).baselineZ).toBeGreaterThan(at(0, 0).baselineZ);
    expect(at(0, 1).inkMinX).toBeGreaterThan(at(0, 0).inkMaxX);
  });

  it("is a plain 3mm slab sized just big enough for its labels", () => {
    expect(layout.thickness).toBe(3);
    expect(DEFAULT_LABEL_SLAB_MARGIN).toBe(3);
    expect(DEFAULT_LABEL_SLAB_GAP).toBe(3);
    // Depth: 3 margin + 6 rows of 5mm + 5 gaps of 3mm + 3 margin.
    expect(layout.depth).toBe(51);
    expect(layout.width).toBeCloseTo(87.4388, 3);
    // The outermost ink sits exactly one margin in from each edge...
    expect(Math.min(...layout.labels.map((label) => label.inkMinX))).toBeCloseTo(3, 9);
    expect(Math.max(...layout.labels.map((label) => label.inkMaxX))).toBeCloseTo(layout.width - 3, 9);
    // ...and every label's digit band does too, top and bottom.
    expect(Math.min(...layout.labels.map((label) => label.baselineZ - LABEL_BAND_TOP))).toBeCloseTo(3, 9);
    expect(Math.max(...layout.labels.map((label) => label.baselineZ - LABEL_BAND_BOTTOM))).toBeCloseTo(layout.depth - 3, 9);
  });

  it("keeps the 3mm gap between every pair of neighbouring labels", () => {
    for (const a of layout.labels) {
      for (const b of layout.labels) {
        if (a.row === b.row && b.column === a.column + 1) expect(b.inkMinX - a.inkMaxX).toBeGreaterThanOrEqual(3 - 1e-9);
        if (a.column === b.column && b.row === a.row + 1) {
          expect(b.baselineZ - LABEL_BAND_TOP - (a.baselineZ - LABEL_BAND_BOTTOM)).toBeCloseTo(3, 9);
        }
      }
    }
  });

  it("fits the Bambu X1C bed (256 x 256mm)", () => {
    expect(layout.width).toBeLessThan(256);
    expect(layout.depth).toBeLessThan(256);
  });

  it("is watertight and manifold (0 boundary edges, 0 non-manifold edges)", () => {
    expect(positions.every(Number.isFinite)).toBe(true);
    const analysis = analyzeTriangleSoup(positions);
    expect(analysis.boundaryEdges).toBe(0);
    expect(analysis.nonManifoldEdges).toBe(0);
    expect(analysis.degenerateTriangles).toBe(0);
  });

  it("exact directed-edge manifold (bit-identical seams, consistent winding)", () => {
    expect(directedEdgeDefects(positions)).toEqual([]);
  });

  it("bounding box is the slab plus the raised labels' 0.8mm", () => {
    const geometry = createLabelSlabGeometry(TEST_PIECE_OPTIONS);
    const box = geometry.boundingBox!;
    expect(box.min.x).toBeCloseTo(0, 6);
    expect(box.max.x).toBeCloseTo(layout.width, 5);
    expect(box.min.y).toBeCloseTo(0, 6);
    expect(box.max.y).toBeCloseTo(3.8, 6);
    expect(box.min.z).toBeCloseTo(0, 6);
    expect(box.max.z).toBeCloseTo(51, 6);
  });

  it("the mesh has exactly four levels: bed, recessed floor, top face, raised face", () => {
    const levels = new Set<number>();
    for (let i = 1; i < positions.length; i += 3) levels.add(positions[i]);
    const sorted = [...levels].sort((a, b) => a - b);
    expect(sorted.length).toBe(4);
    expect(sorted[0]).toBe(0);
    expect(sorted[2]).toBe(3);
    expect(LABEL_DEPTH).toBe(0.8);
    expect(sorted[2] - sorted[1]).toBeCloseTo(0.8, 12);
    expect(sorted[3] - sorted[2]).toBeCloseTo(0.8, 12);
  });

  // Every label appears once raised and once recessed, so what the raised
  // ones add is exactly what the recessed ones remove.
  it("volume equals the plain slab's", () => {
    const analysis = analyzeTriangleSoup(positions);
    expect(Math.abs(analysis.volume)).toBeCloseTo(layout.width * layout.depth * layout.thickness, 6);
  });
});

// A sealed-shut groove, or a raised label that was never raised, is still a
// perfectly valid closed solid (CLAUDE-LESSONS.md). So raycast the EXPORTED
// FILE: on a fine grid over every label, the surface must stand at 3.8mm
// over a raised stroke, 2.2mm over a recessed stroke, and 3mm everywhere
// else -- between glyphs, between labels, and inside every counter -- with
// solid material all the way down to the bed beneath it.
describe("test-prints/label-test-piece.stl", () => {
  const file = readFileSync(TEST_PIECE_PATH, "utf8");
  const filePositions = parseStlToScenePositions(file);
  const layout = labelSlabLayout(TEST_PIECE_OPTIONS);

  it("is exactly what the module produces, byte for byte", () => {
    const expected = toStlText(labelSlabPositions(TEST_PIECE_OPTIONS));
    expect(file.length).toBe(expected.length);
    expect(file === expected).toBe(true);
    expect(file.split("\n").filter((line) => line.startsWith("  facet normal")).length).toBe(40864);
  });

  it("the file itself is watertight, manifold and exact directed-edge manifold", () => {
    const analysis = analyzeTriangleSoup(filePositions);
    expect(analysis.triangleCount).toBe(40864);
    expect(analysis.boundaryEdges).toBe(0);
    expect(analysis.nonManifoldEdges).toBe(0);
    expect(analysis.degenerateTriangles).toBe(0);
    expect(directedEdgeDefects(filePositions)).toEqual([]);
  });

  it("raised where raised, recessed where recessed, flat everywhere else, solid underneath", () => {
    const STEP = 0.21;
    const KEEP_OFF_OUTLINE = 0.02;
    let strokeSamples = 0;
    let counterSamples = 0;
    let flatSamples = 0;
    for (const label of layout.labels) {
      // Non-vertical triangles whose plan bounding box touches this cell.
      const triangles: number[][] = [];
      for (let i = 0; i + 8 < filePositions.length; i += 9) {
        const t = filePositions.slice(i, i + 9);
        const denom = (t[5] - t[8]) * (t[0] - t[6]) + (t[6] - t[3]) * (t[2] - t[8]);
        if (Math.abs(denom) < 1e-12) continue;
        if (Math.max(t[0], t[3], t[6]) < label.cellMinX || Math.min(t[0], t[3], t[6]) > label.cellMaxX) continue;
        if (Math.max(t[2], t[5], t[8]) < label.cellMinZ || Math.min(t[2], t[5], t[8]) > label.cellMaxZ) continue;
        triangles.push(t);
      }
      let labelStrokeSamples = 0;
      for (let x = label.cellMinX + 0.0137; x < label.cellMaxX; x += STEP) {
        for (let z = label.cellMinZ + 0.0071; z < label.cellMaxZ; z += STEP) {
          let nearOutline = false;
          let inStroke = false;
          let inCounter = false;
          for (const glyph of label.glyphs) {
            for (const loop of allLoops(glyph)) if (distanceToLoop(loop, x, z) < KEEP_OFF_OUTLINE) nearOutline = true;
            if (pointInLoop(glyph.outer, x, z)) {
              if (glyph.holes.some((hole) => pointInLoop(hole, x, z))) inCounter = true;
              else inStroke = true;
            }
          }
          if (nearOutline) continue;
          const expectedTop = !inStroke ? 3 : label.style === "raised" ? 3 + LABEL_DEPTH : 3 - LABEL_DEPTH;

          const crossings: number[] = [];
          for (const t of triangles) {
            const denom = (t[5] - t[8]) * (t[0] - t[6]) + (t[6] - t[3]) * (t[2] - t[8]);
            const a = ((t[5] - t[8]) * (x - t[6]) + (t[6] - t[3]) * (z - t[8])) / denom;
            const b = ((t[8] - t[2]) * (x - t[6]) + (t[0] - t[6]) * (z - t[8])) / denom;
            const c = 1 - a - b;
            if (a < 0 || b < 0 || c < 0) continue;
            crossings.push(a * t[1] + b * t[4] + c * t[7]);
          }
          crossings.sort((m, n) => m - n);
          const distinct = crossings.filter((y, index) => index === 0 || y - crossings[index - 1] > 1e-9);
          // Exactly two surfaces on the way down: the expected top, and the
          // bed face. Nothing in between -- solid all the way.
          if (distinct.length !== 2 || Math.abs(distinct[0]) > 1e-9 || Math.abs(distinct[1] - expectedTop) > 1e-9) {
            throw new Error(
              `"${label.text}" ${label.style} at x=${x.toFixed(3)} z=${z.toFixed(3)}: expected surfaces [0, ${expectedTop}], found [${distinct.join(", ")}]`,
            );
          }
          if (inStroke) {
            strokeSamples += 1;
            labelStrokeSamples += 1;
          } else if (inCounter) counterSamples += 1;
          else flatSamples += 1;
        }
      }
      // Not vacuous: every label's strokes were actually sampled.
      expect(labelStrokeSamples, `"${label.text}" ${label.style} stroke samples`).toBeGreaterThan(100);
    }
    expect(strokeSamples).toBeGreaterThan(5000);
    expect(counterSamples).toBeGreaterThan(100);
    expect(flatSamples).toBeGreaterThan(20000);
  });
});

describe("labelSlabLayout: validation", () => {
  const one = (overrides: Partial<LabelSlabOptions> = {}): LabelSlabOptions => ({ rows: [[{ text: "5mm", style: "recessed" }]], ...overrides });

  it("throws when a recessed label would leave less than the 2mm minimum floor", () => {
    expect(() => labelSlabLayout(one({ thickness: 2.7 }))).toThrow(/less than the 2mm minimum floor/);
    expect(() => labelSlabLayout(one({ thickness: 2.8 }))).not.toThrow();
    // A raised label cuts nothing, so the same thin slab is fine.
    expect(() => labelSlabLayout({ thickness: 1, rows: [[{ text: "5mm", style: "raised" }]] })).not.toThrow();
  });

  it("throws on a non-positive thickness, margin or gap", () => {
    expect(() => labelSlabLayout(one({ thickness: 0 }))).toThrow(/thickness must be positive/);
    expect(() => labelSlabLayout(one({ margin: 0 }))).toThrow(/margin must be positive/);
    expect(() => labelSlabLayout(one({ gap: -1 }))).toThrow(/gap must be positive/);
  });

  it("throws on no labels, ragged rows, an unknown style, or an unsupported character", () => {
    expect(() => labelSlabLayout({ rows: [] })).toThrow(/at least one row/);
    expect(() => labelSlabLayout({ rows: [[]] })).toThrow(/at least one row/);
    expect(() =>
      labelSlabLayout({
        rows: [
          [
            { text: "5mm", style: "raised" },
            { text: "6mm", style: "raised" },
          ],
          [{ text: "7mm", style: "raised" }],
        ],
      }),
    ).toThrow(/row 1: holds 1 labels, but row 0 holds 2/);
    expect(() => labelSlabLayout({ rows: [[{ text: "5mm", style: "engraved" as LabelStyle }]] })).toThrow(/style must be "raised" or "recessed"/);
    expect(() => labelSlabLayout({ rows: [[{ text: "5 mm", style: "raised" }]] })).toThrow(/row 0 column 0: label "5 mm" contains " "/);
  });

  it("sizes each column to its widest label and left-aligns the rest by their ink", () => {
    const layout = labelSlabLayout({
      rows: [[{ text: "5mm", style: "raised" }], [{ text: "16mm", style: "raised" }]],
    });
    const [narrow, wide] = layout.labels;
    expect(narrow.inkMinX).toBeCloseTo(3, 9);
    expect(wide.inkMinX).toBeCloseTo(3, 9);
    expect(wide.inkMaxX).toBeCloseTo(layout.width - 3, 9);
    expect(narrow.inkMaxX).toBeLessThan(wide.inkMaxX);
  });
});
