import { describe, expect, it } from "vitest";
import * as THREE from "three";
import {
  createSocketTrayGeometry,
  normalizeSocketTrayDepth,
  normalizeSocketTrayThickness,
  normalizeSocketTrayWidth,
  socketTrayPositions,
  type SocketTrayOptions,
  type SocketTrayPocket,
} from "@/lib/socketTrayGeometry";
import { analyzeTriangleSoup } from "@/lib/svgImport";

// Converts a raw positions array to ASCII STL text (same coordinate
// convention as stlExport.ts / scripts/generate-socket-tray-sampler.mjs:
// scene [x, y, z] -> file [x, -z, y]) and immediately parses that TEXT back
// into a positions array in scene coordinates -- an actual STL round-trip,
// not a re-use of the in-memory geometry, per KNOWN-FIXES.md's "raycast the
// exported STL, don't trust mesh checks alone."
function toStlText(positions: readonly number[]): string {
  const lines = ["solid socket_tray_rounding_test"];
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const toZUp = (x: number, y: number, z: number) => [x, -z, y] as const;
    const a = toZUp(positions[i], positions[i + 1], positions[i + 2]);
    const b = toZUp(positions[i + 3], positions[i + 4], positions[i + 5]);
    const c = toZUp(positions[i + 6], positions[i + 7], positions[i + 8]);
    lines.push("  facet normal 0 0 0", "    outer loop", `      vertex ${a[0]} ${a[1]} ${a[2]}`, `      vertex ${b[0]} ${b[1]} ${b[2]}`, `      vertex ${c[0]} ${c[1]} ${c[2]}`, "    endloop", "  endfacet");
  }
  lines.push("endsolid socket_tray_rounding_test");
  return lines.join("\n");
}

function parseStlToScenePositions(stl: string): number[] {
  const positions: number[] = [];
  const vertexPattern = /vertex\s+(-?[\d.eE+-]+)\s+(-?[\d.eE+-]+)\s+(-?[\d.eE+-]+)/g;
  let match: RegExpExecArray | null;
  while ((match = vertexPattern.exec(stl))) {
    const fx = Number(match[1]);
    const fy = Number(match[2]);
    const fz = Number(match[3]);
    // Inverse of [x, y, z] -> [x, -z, y]: scene x = file x, scene y = file z, scene z = -file y.
    positions.push(fx, fz, -fy);
  }
  return positions;
}

// Mirrors the socket-tray-sampler.stl coupon generated by
// scripts/generate-socket-tray-sampler.mjs -- same width/depth/thickness and
// the same 6 pockets, so this test exercises exactly the geometry that gets
// printed. See reference/socket-tray-sampler-report.md for the reasoning
// behind these numbers. Pocket depth 14mm + 4mm floor = 18mm tray thickness
// (unchanged). Diameters are real measured socket ODs + 2mm clearance (not
// estimates): 14, 15, 19, 20.70, 23, 25mm, left to right -- up from 5
// pockets to 6. Pitch dropped from 45mm to 36mm (margins unchanged at
// 30mm each side) to keep the 6-pocket tray at 240mm wide, comfortably
// under the Bambu X1C's 256mm bed; see the report for the bed-fit math.
const SAMPLER_POCKETS: SocketTrayPocket[] = [
  { diameter: 14, depth: 14, x: 30, z: 30 },
  { diameter: 15, depth: 14, x: 66, z: 30 },
  { diameter: 19, depth: 14, x: 102, z: 30 },
  { diameter: 20.7, depth: 14, x: 138, z: 30 },
  { diameter: 23, depth: 14, x: 174, z: 30 },
  { diameter: 25, depth: 14, x: 210, z: 30 },
];
const SAMPLER_OPTIONS: SocketTrayOptions = { width: 240, depth: 60, thickness: 18, pockets: SAMPLER_POCKETS };

describe("socketTrayPositions: sampler coupon", () => {
  it("is watertight and manifold (0 boundary edges, 0 non-manifold edges)", () => {
    const positions = socketTrayPositions(SAMPLER_OPTIONS);
    expect(positions.every(Number.isFinite)).toBe(true);
    const analysis = analyzeTriangleSoup(positions);
    expect(analysis.boundaryEdges).toBe(0);
    expect(analysis.nonManifoldEdges).toBe(0);
  });

  // Stricter than the spatially-quantized check above -- every directed edge
  // must appear exactly once, with its reverse exactly once, on the raw
  // double coordinates. Only holds if every stitched seam (top-cap notch
  // <-> pocket wall top ring, pocket wall bottom <-> floor cap) reuses
  // bit-identical vertex coordinates and every winding is consistent -- the
  // exact-stitch contract from CLAUDE-LESSONS.md.
  it("exact directed-edge manifold (bit-identical seams, consistent winding)", () => {
    const positions = socketTrayPositions(SAMPLER_OPTIONS);
    const directed = new Map<string, number>();
    for (let i = 0; i + 8 < positions.length; i += 9) {
      const keys = [0, 3, 6].map((offset) => `${positions[i + offset]},${positions[i + offset + 1]},${positions[i + offset + 2]}`);
      for (let edge = 0; edge < 3; edge += 1) {
        const key = `${keys[edge]}|${keys[(edge + 1) % 3]}`;
        directed.set(key, (directed.get(key) ?? 0) + 1);
      }
    }
    for (const [key, count] of directed) {
      expect(count, `directed edge ${key} should appear exactly once`).toBe(1);
      const [a, b] = key.split("|");
      expect(directed.get(`${b}|${a}`), `reverse of ${key} should appear exactly once`).toBe(1);
    }
  });

  it("bounding box matches the requested tray dimensions", () => {
    const geometry = createSocketTrayGeometry(SAMPLER_OPTIONS);
    geometry.computeBoundingBox();
    const box = geometry.boundingBox!;
    expect(box.min.x).toBeCloseTo(0, 6);
    expect(box.max.x).toBeCloseTo(240, 6);
    expect(box.min.y).toBeCloseTo(0, 6);
    expect(box.max.y).toBeCloseTo(18, 6);
    expect(box.min.z).toBeCloseTo(0, 6);
    expect(box.max.z).toBeCloseTo(60, 6);
  });
});

// A sealed-shut pocket still passes the manifold check above -- it's a
// perfectly valid closed solid, just the WRONG one (CLAUDE-LESSONS.md).
// Raycast the actual geometry instead: vertically at each pocket's center,
// confirm the pocket is OPEN from the top face down to its floor and SOLID
// from the floor down to the tray's bottom face; at a point between
// pockets, confirm the tray is solid top to bottom (no accidental opening).
function verticalCrossings(geometry: THREE.BufferGeometry, x: number, z: number): number[] {
  const position = geometry.getAttribute("position");
  const crossings: number[] = [];
  for (let i = 0; i < position.count; i += 3) {
    const p0: [number, number, number] = [position.getX(i), position.getY(i), position.getZ(i)];
    const p1: [number, number, number] = [position.getX(i + 1), position.getY(i + 1), position.getZ(i + 1)];
    const p2: [number, number, number] = [position.getX(i + 2), position.getY(i + 2), position.getZ(i + 2)];
    // Barycentric solve in (X, Z) for the ray x=const, z=const running along Y.
    const denom = (p1[2] - p2[2]) * (p0[0] - p2[0]) + (p2[0] - p1[0]) * (p0[2] - p2[2]);
    if (Math.abs(denom) < 1e-9) continue;
    const a = ((p1[2] - p2[2]) * (x - p2[0]) + (p2[0] - p1[0]) * (z - p2[2])) / denom;
    const b = ((p2[2] - p0[2]) * (x - p2[0]) + (p0[0] - p2[0]) * (z - p2[2])) / denom;
    const c = 1 - a - b;
    if (a < -1e-6 || b < -1e-6 || c < -1e-6) continue;
    crossings.push(a * p0[1] + b * p1[1] + c * p2[1]);
  }
  crossings.sort((m, n) => m - n);
  // A sample point that lands exactly on an internal edge of a flat face's
  // own earcut triangulation (e.g. the diagonal splitting the top face's
  // rectangle-with-holes contour into triangles) registers a hit from both
  // triangles sharing that edge -- same physical surface, same Y, not a
  // second layer of material. Merge crossings within float noise of each
  // other; real distinct layers here (bottom / pocket floor / top) are mm
  // apart, so this can't hide an actual double wall.
  const merged: number[] = [];
  for (const y of crossings) {
    if (merged.length === 0 || Math.abs(y - merged[merged.length - 1]) > 1e-6) merged.push(y);
  }
  return merged;
}

// Same barycentric vertical-ray solve as verticalCrossings below, but over a
// raw positions array instead of a THREE.BufferGeometry -- used for the
// exported-STL raycast, which has no BufferGeometry to hand.
function verticalCrossingsFromPositions(positions: readonly number[], x: number, z: number): number[] {
  const crossings: number[] = [];
  for (let i = 0; i + 8 < positions.length; i += 9) {
    const p0: [number, number, number] = [positions[i], positions[i + 1], positions[i + 2]];
    const p1: [number, number, number] = [positions[i + 3], positions[i + 4], positions[i + 5]];
    const p2: [number, number, number] = [positions[i + 6], positions[i + 7], positions[i + 8]];
    const denom = (p1[2] - p2[2]) * (p0[0] - p2[0]) + (p2[0] - p1[0]) * (p0[2] - p2[2]);
    if (Math.abs(denom) < 1e-9) continue;
    const a = ((p1[2] - p2[2]) * (x - p2[0]) + (p2[0] - p1[0]) * (z - p2[2])) / denom;
    const b = ((p2[2] - p0[2]) * (x - p2[0]) + (p0[0] - p2[0]) * (z - p2[2])) / denom;
    const c = 1 - a - b;
    if (a < -1e-6 || b < -1e-6 || c < -1e-6) continue;
    crossings.push(a * p0[1] + b * p1[1] + c * p2[1]);
  }
  crossings.sort((m, n) => m - n);
  const merged: number[] = [];
  for (const y of crossings) {
    if (merged.length === 0 || Math.abs(y - merged[merged.length - 1]) > 1e-6) merged.push(y);
  }
  return merged;
}

describe("socketTrayPositions: corner radius (fillet)", () => {
  // Regression anchor: with cornerRadius 0 (or omitted), output must be
  // byte-identical to the pre-rounding module -- proven here as an exact
  // array comparison, and structurally guaranteed by the module's own
  // radius===0 branch being the original, untouched code path.
  it("radius 0 is identical to omitting cornerRadius entirely", () => {
    const withZero = socketTrayPositions({ ...SAMPLER_OPTIONS, cornerRadius: 0 });
    const omitted = socketTrayPositions(SAMPLER_OPTIONS);
    expect(withZero).toEqual(omitted);
  });

  it("radius 0 on the sampler is identical to the original 17-test sampler geometry", () => {
    const rounded = socketTrayPositions({ ...SAMPLER_OPTIONS, cornerRadius: 0 });
    const original = socketTrayPositions(SAMPLER_OPTIONS);
    expect(rounded.length).toBe(original.length);
    expect(rounded).toEqual(original);
  });

  describe("valid nonzero radius", () => {
    const ROUNDED_OPTIONS: SocketTrayOptions = { ...SAMPLER_OPTIONS, cornerRadius: 3 };
    const positions = socketTrayPositions(ROUNDED_OPTIONS);

    it("is watertight and manifold (0 boundary edges, 0 non-manifold edges)", () => {
      expect(positions.every(Number.isFinite)).toBe(true);
      const analysis = analyzeTriangleSoup(positions);
      expect(analysis.boundaryEdges).toBe(0);
      expect(analysis.nonManifoldEdges).toBe(0);
    });

    it("exact directed-edge manifold (bit-identical seams, consistent winding)", () => {
      const directed = new Map<string, number>();
      for (let i = 0; i + 8 < positions.length; i += 9) {
        const keys = [0, 3, 6].map((offset) => `${positions[i + offset]},${positions[i + offset + 1]},${positions[i + offset + 2]}`);
        for (let edge = 0; edge < 3; edge += 1) {
          const key = `${keys[edge]}|${keys[(edge + 1) % 3]}`;
          directed.set(key, (directed.get(key) ?? 0) + 1);
        }
      }
      for (const [key, count] of directed) {
        expect(count, `directed edge ${key} should appear exactly once`).toBe(1);
        const [a, b] = key.split("|");
        expect(directed.get(`${b}|${a}`), `reverse of ${key} should appear exactly once`).toBe(1);
      }
    });

    it("bounding box is unchanged by the fillet (it recedes inward, never grows outward)", () => {
      const geometry = createSocketTrayGeometry(ROUNDED_OPTIONS);
      geometry.computeBoundingBox();
      const box = geometry.boundingBox!;
      expect(box.min.x).toBeCloseTo(0, 6);
      expect(box.max.x).toBeCloseTo(240, 6);
      expect(box.min.y).toBeCloseTo(0, 6);
      expect(box.max.y).toBeCloseTo(18, 6);
      expect(box.min.z).toBeCloseTo(0, 6);
      expect(box.max.z).toBeCloseTo(60, 6);
    });

    // Per the recon's flagged risk: a rim fillet could reseal a pocket while
    // every check above still passes (a sealed pocket is a perfectly valid
    // closed manifold). Raycast the actual EXPORTED STL -- an ASCII
    // round-trip through toStlText/parseStlToScenePositions, not the
    // in-memory geometry -- at every pocket. The rim now widens to
    // (radius + cornerRadius) at the very top face and narrows back to the
    // nominal radius cornerRadius below it, so "open top-to-floor" is
    // re-verified at the pocket's own center (always inside the narrowest,
    // nominal-radius bore) rather than reusing the pre-rounding off-center
    // offsets, which could land inside the new fillet material near the top.
    it.each(SAMPLER_POCKETS)("pocket d=$diameter, rounded (cornerRadius=3): open top-to-floor, solid floor-to-bottom, at its exact center, on the EXPORTED STL", (pocket) => {
      const exported = parseStlToScenePositions(toStlText(positions));
      const crossings = verticalCrossingsFromPositions(exported, pocket.x, pocket.z);
      const topY = 18;
      const floorY = topY - pocket.depth;
      expect(crossings.length).toBe(2);
      expect(crossings[0]).toBeCloseTo(0, 3);
      expect(crossings[1]).toBeCloseTo(floorY, 3);
    });

    it("between pockets, the exported STL is still a solid slab top to bottom", () => {
      const exported = parseStlToScenePositions(toStlText(positions));
      for (const x of [48, 84, 120, 156, 192]) {
        const crossings = verticalCrossingsFromPositions(exported, x, 30);
        expect(crossings.length).toBe(2);
        expect(crossings[0]).toBeCloseTo(0, 3);
        expect(crossings[1]).toBeCloseTo(18, 3);
      }
    });

    it("near an outer top edge, material height is reduced by the fillet but never sealed shut (open above, solid below)", () => {
      const exported = parseStlToScenePositions(toStlText(positions));
      // 1mm from the left edge, at cornerRadius=3 the top face itself starts
      // at x=3, so material here should read shorter than the full 18mm.
      const crossings = verticalCrossingsFromPositions(exported, 1, 30);
      expect(crossings.length).toBe(2);
      expect(crossings[0]).toBeCloseTo(0, 3);
      expect(crossings[1]).toBeLessThan(18);
      expect(crossings[1]).toBeGreaterThan(15);
    });
  });

  describe("validation", () => {
    it("throws when the corner radius is too large for the tray's footprint", () => {
      expect(() => socketTrayPositions({ width: 20, depth: 60, thickness: 18, cornerRadius: 15 })).toThrow(/footprint/);
    });

    it("throws when the corner radius leaves no straight wall below it at the tray's thickness", () => {
      expect(() => socketTrayPositions({ width: 240, depth: 60, thickness: 5, cornerRadius: 6 })).toThrow(/straight wall/);
    });

    it("throws when the corner radius leaves no straight wall below it in a pocket (too large relative to pocket depth)", () => {
      expect(() => socketTrayPositions({ width: 240, depth: 60, thickness: 18, cornerRadius: 15, pockets: [{ diameter: 20, depth: 14, x: 100, z: 30 }] })).toThrow(/straight wall/);
    });

    it("throws when the corner radius widens a pocket (too large relative to the pocket's diameter) into the tray edge", () => {
      expect(() => socketTrayPositions({ width: 240, depth: 60, thickness: 18, cornerRadius: 4, pockets: [{ diameter: 20, depth: 14, x: 15, z: 30 }] })).toThrow(/edge/);
    });

    it("throws when the corner radius widens a pocket (too large relative to the pocket's diameter) into a neighboring pocket", () => {
      expect(() =>
        socketTrayPositions({
          width: 240,
          depth: 60,
          thickness: 18,
          cornerRadius: 3,
          pockets: [
            { diameter: 20, depth: 14, x: 100, z: 30 },
            { diameter: 20, depth: 14, x: 126, z: 30 },
          ],
        }),
      ).toThrow(/pocket 1/);
    });

    it("throws on a negative corner radius", () => {
      expect(() => socketTrayPositions({ cornerRadius: -1 })).toThrow(/zero or positive/);
    });
  });
});

describe("socketTrayPositions: sampler coupon pockets are open blind pockets, not sealed or through-holes", () => {
  const geometry = createSocketTrayGeometry(SAMPLER_OPTIONS);
  const topY = 18;

  it.each(SAMPLER_POCKETS)("pocket d=$diameter: open top-to-floor, solid floor-to-bottom, at its exact center", (pocket) => {
    const crossings = verticalCrossings(geometry, pocket.x, pocket.z);
    const floorY = topY - pocket.depth;
    expect(crossings.length).toBe(2);
    expect(crossings[0]).toBeCloseTo(0, 4); // tray bottom face
    expect(crossings[1]).toBeCloseTo(floorY, 4); // pocket floor -- NOT topY, i.e. genuinely open above it
  });

  it("between pockets, the tray is a solid slab (no accidental opening)", () => {
    const midpoints = [48, 84, 120, 156, 192]; // between adjacent pocket centers along X (pitch 36mm), z=30 (row centerline)
    for (const x of midpoints) {
      const crossings = verticalCrossings(geometry, x, 30);
      expect(crossings.length).toBe(2);
      expect(crossings[0]).toBeCloseTo(0, 4);
      expect(crossings[1]).toBeCloseTo(topY, 4);
    }
  });

  // The tightest pocket-to-pocket gap in this layout is between the two
  // largest neighboring pockets (23mm and 25mm, 12mm of material between
  // their rims at 36mm pitch) -- the pair the reduced pitch was most likely
  // to squeeze. Explicitly confirm solid material at that specific
  // midpoint, not just as one entry in the generic sweep above.
  it("solid material between the two largest neighboring pockets (23mm and 25mm)", () => {
    const midX = (174 + 210) / 2; // (23mm pocket center + 25mm pocket center) / 2
    const crossings = verticalCrossings(geometry, midX, 30);
    expect(crossings.length).toBe(2);
    expect(crossings[0]).toBeCloseTo(0, 4);
    expect(crossings[1]).toBeCloseTo(topY, 4);
  });

  it("off-center inside the largest pocket (25mm), still open top-to-floor", () => {
    const largest = SAMPLER_POCKETS[SAMPLER_POCKETS.length - 1];
    const offset = largest.diameter / 2 - 3; // 3mm in from the rim, well clear of the wall
    const crossings = verticalCrossings(geometry, largest.x + offset, largest.z);
    expect(crossings.length).toBe(2);
    expect(crossings[0]).toBeCloseTo(0, 4);
    expect(crossings[1]).toBeCloseTo(topY - largest.depth, 4);
  });

  // 10mm was the smallest pocket the prior (10-27mm) coupon exercised; this
  // pass's smallest is 14mm. Keep the off-center probe for whichever pocket
  // is currently smallest, the same way the largest pocket is probed above,
  // in case a minimum-size edge case only shows up away from the axis.
  it("off-center inside the smallest pocket (14mm), still open top-to-floor", () => {
    const smallest = SAMPLER_POCKETS[0];
    const offset = smallest.diameter / 2 - 3; // 3mm in from the rim, well clear of the wall
    const crossings = verticalCrossings(geometry, smallest.x + offset, smallest.z);
    expect(crossings.length).toBe(2);
    expect(crossings[0]).toBeCloseTo(0, 4);
    expect(crossings[1]).toBeCloseTo(topY - smallest.depth, 4);
  });
});

describe("socketTrayPositions: validation", () => {
  it("throws when a pocket's floor would be thinner than the minimum", () => {
    expect(() => socketTrayPositions({ width: 240, depth: 60, thickness: 20, pockets: [{ diameter: 20, depth: 19, x: 100, z: 30 }] })).toThrow(/floor/);
  });

  it("throws when a pocket footprint is too close to the tray edge", () => {
    expect(() => socketTrayPositions({ width: 240, depth: 60, thickness: 24, pockets: [{ diameter: 20, depth: 10, x: 8, z: 30 }] })).toThrow(/edge/);
  });

  it("throws when two pockets overlap or leave too thin a dividing wall", () => {
    expect(() =>
      socketTrayPositions({
        width: 240,
        depth: 60,
        thickness: 24,
        pockets: [
          { diameter: 20, depth: 10, x: 100, z: 30 },
          { diameter: 20, depth: 10, x: 110, z: 30 },
        ],
      }),
    ).toThrow(/overlap/);
  });

  it("normalize helpers fall back to defaults for undefined and throw on non-positive values", () => {
    expect(normalizeSocketTrayWidth(undefined)).toBe(240);
    expect(normalizeSocketTrayDepth(undefined)).toBe(60);
    expect(normalizeSocketTrayThickness(undefined)).toBe(18);
    expect(() => normalizeSocketTrayWidth(0)).toThrow();
  });
});
