import { describe, expect, it } from "vitest";
import * as THREE from "three";
import {
  createSocketTrayGeometry,
  normalizeSocketTrayDepth,
  normalizeSocketTrayThickness,
  normalizeSocketTrayWidth,
  socketTrayPositions,
  type SocketTrayOptions,
  type SocketTrayPocket,
} from "@/lib/socketTrayGeometry";
import { analyzeTriangleSoup } from "@/lib/svgImport";

// Mirrors the socket-tray-sampler.stl coupon generated by
// scripts/generate-socket-tray-sampler.mjs -- same width/depth/thickness and
// the same 5 pockets, so this test exercises exactly the geometry that gets
// printed. See reference/socket-tray-sampler-report.md for the reasoning
// behind these numbers. Pocket depth 14mm + 4mm floor = 18mm tray thickness
// (reduced from the first 20mm-deep/24mm-thick coupon).
const SAMPLER_POCKETS: SocketTrayPocket[] = [
  { diameter: 15, depth: 14, x: 30, z: 30 },
  { diameter: 18, depth: 14, x: 75, z: 30 },
  { diameter: 22, depth: 14, x: 120, z: 30 },
  { diameter: 25, depth: 14, x: 165, z: 30 },
  { diameter: 28, depth: 14, x: 210, z: 30 },
];
const SAMPLER_OPTIONS: SocketTrayOptions = { width: 240, depth: 60, thickness: 18, pockets: SAMPLER_POCKETS };

describe("socketTrayPositions: sampler coupon", () => {
  it("is watertight and manifold (0 boundary edges, 0 non-manifold edges)", () => {
    const positions = socketTrayPositions(SAMPLER_OPTIONS);
    expect(positions.every(Number.isFinite)).toBe(true);
    const analysis = analyzeTriangleSoup(positions);
    expect(analysis.boundaryEdges).toBe(0);
    expect(analysis.nonManifoldEdges).toBe(0);
  });

  // Stricter than the spatially-quantized check above -- every directed edge
  // must appear exactly once, with its reverse exactly once, on the raw
  // double coordinates. Only holds if every stitched seam (top-cap notch
  // <-> pocket wall top ring, pocket wall bottom <-> floor cap) reuses
  // bit-identical vertex coordinates and every winding is consistent -- the
  // exact-stitch contract from CLAUDE-LESSONS.md.
  it("exact directed-edge manifold (bit-identical seams, consistent winding)", () => {
    const positions = socketTrayPositions(SAMPLER_OPTIONS);
    const directed = new Map<string, number>();
    for (let i = 0; i + 8 < positions.length; i += 9) {
      const keys = [0, 3, 6].map((offset) => `${positions[i + offset]},${positions[i + offset + 1]},${positions[i + offset + 2]}`);
      for (let edge = 0; edge < 3; edge += 1) {
        const key = `${keys[edge]}|${keys[(edge + 1) % 3]}`;
        directed.set(key, (directed.get(key) ?? 0) + 1);
      }
    }
    for (const [key, count] of directed) {
      expect(count, `directed edge ${key} should appear exactly once`).toBe(1);
      const [a, b] = key.split("|");
      expect(directed.get(`${b}|${a}`), `reverse of ${key} should appear exactly once`).toBe(1);
    }
  });

  it("bounding box matches the requested tray dimensions", () => {
    const geometry = createSocketTrayGeometry(SAMPLER_OPTIONS);
    geometry.computeBoundingBox();
    const box = geometry.boundingBox!;
    expect(box.min.x).toBeCloseTo(0, 6);
    expect(box.max.x).toBeCloseTo(240, 6);
    expect(box.min.y).toBeCloseTo(0, 6);
    expect(box.max.y).toBeCloseTo(18, 6);
    expect(box.min.z).toBeCloseTo(0, 6);
    expect(box.max.z).toBeCloseTo(60, 6);
  });
});

// A sealed-shut pocket still passes the manifold check above -- it's a
// perfectly valid closed solid, just the WRONG one (CLAUDE-LESSONS.md).
// Raycast the actual geometry instead: vertically at each pocket's center,
// confirm the pocket is OPEN from the top face down to its floor and SOLID
// from the floor down to the tray's bottom face; at a point between
// pockets, confirm the tray is solid top to bottom (no accidental opening).
function verticalCrossings(geometry: THREE.BufferGeometry, x: number, z: number): number[] {
  const position = geometry.getAttribute("position");
  const crossings: number[] = [];
  for (let i = 0; i < position.count; i += 3) {
    const p0: [number, number, number] = [position.getX(i), position.getY(i), position.getZ(i)];
    const p1: [number, number, number] = [position.getX(i + 1), position.getY(i + 1), position.getZ(i + 1)];
    const p2: [number, number, number] = [position.getX(i + 2), position.getY(i + 2), position.getZ(i + 2)];
    // Barycentric solve in (X, Z) for the ray x=const, z=const running along Y.
    const denom = (p1[2] - p2[2]) * (p0[0] - p2[0]) + (p2[0] - p1[0]) * (p0[2] - p2[2]);
    if (Math.abs(denom) < 1e-9) continue;
    const a = ((p1[2] - p2[2]) * (x - p2[0]) + (p2[0] - p1[0]) * (z - p2[2])) / denom;
    const b = ((p2[2] - p0[2]) * (x - p2[0]) + (p0[0] - p2[0]) * (z - p2[2])) / denom;
    const c = 1 - a - b;
    if (a < -1e-6 || b < -1e-6 || c < -1e-6) continue;
    crossings.push(a * p0[1] + b * p1[1] + c * p2[1]);
  }
  crossings.sort((m, n) => m - n);
  // A sample point that lands exactly on an internal edge of a flat face's
  // own earcut triangulation (e.g. the diagonal splitting the top face's
  // rectangle-with-holes contour into triangles) registers a hit from both
  // triangles sharing that edge -- same physical surface, same Y, not a
  // second layer of material. Merge crossings within float noise of each
  // other; real distinct layers here (bottom / pocket floor / top) are mm
  // apart, so this can't hide an actual double wall.
  const merged: number[] = [];
  for (const y of crossings) {
    if (merged.length === 0 || Math.abs(y - merged[merged.length - 1]) > 1e-6) merged.push(y);
  }
  return merged;
}

describe("socketTrayPositions: sampler coupon pockets are open blind pockets, not sealed or through-holes", () => {
  const geometry = createSocketTrayGeometry(SAMPLER_OPTIONS);
  const topY = 18;

  it.each(SAMPLER_POCKETS)("pocket d=$diameter: open top-to-floor, solid floor-to-bottom, at its exact center", (pocket) => {
    const crossings = verticalCrossings(geometry, pocket.x, pocket.z);
    const floorY = topY - pocket.depth;
    expect(crossings.length).toBe(2);
    expect(crossings[0]).toBeCloseTo(0, 4); // tray bottom face
    expect(crossings[1]).toBeCloseTo(floorY, 4); // pocket floor -- NOT topY, i.e. genuinely open above it
  });

  it("between pockets, the tray is a solid slab (no accidental opening)", () => {
    const midpoints = [52.5, 97.5, 142.5, 187.5]; // between adjacent pocket centers along X, z=30 (row centerline)
    for (const x of midpoints) {
      const crossings = verticalCrossings(geometry, x, 30);
      expect(crossings.length).toBe(2);
      expect(crossings[0]).toBeCloseTo(0, 4);
      expect(crossings[1]).toBeCloseTo(topY, 4);
    }
  });

  it("off-center inside the largest pocket (28mm), still open top-to-floor", () => {
    const largest = SAMPLER_POCKETS[SAMPLER_POCKETS.length - 1];
    const offset = largest.diameter / 2 - 3; // 3mm in from the rim, well clear of the wall
    const crossings = verticalCrossings(geometry, largest.x + offset, largest.z);
    expect(crossings.length).toBe(2);
    expect(crossings[0]).toBeCloseTo(0, 4);
    expect(crossings[1]).toBeCloseTo(topY - largest.depth, 4);
  });
});

describe("socketTrayPositions: validation", () => {
  it("throws when a pocket's floor would be thinner than the minimum", () => {
    expect(() => socketTrayPositions({ width: 240, depth: 60, thickness: 20, pockets: [{ diameter: 20, depth: 19, x: 100, z: 30 }] })).toThrow(/floor/);
  });

  it("throws when a pocket footprint is too close to the tray edge", () => {
    expect(() => socketTrayPositions({ width: 240, depth: 60, thickness: 24, pockets: [{ diameter: 20, depth: 10, x: 8, z: 30 }] })).toThrow(/edge/);
  });

  it("throws when two pockets overlap or leave too thin a dividing wall", () => {
    expect(() =>
      socketTrayPositions({
        width: 240,
        depth: 60,
        thickness: 24,
        pockets: [
          { diameter: 20, depth: 10, x: 100, z: 30 },
          { diameter: 20, depth: 10, x: 110, z: 30 },
        ],
      }),
    ).toThrow(/overlap/);
  });

  it("normalize helpers fall back to defaults for undefined and throw on non-positive values", () => {
    expect(normalizeSocketTrayWidth(undefined)).toBe(240);
    expect(normalizeSocketTrayDepth(undefined)).toBe(60);
    expect(normalizeSocketTrayThickness(undefined)).toBe(18);
    expect(() => normalizeSocketTrayWidth(0)).toThrow();
  });
});
